/**
 * Tests for the examples the application ships, and for its catalogue.
 *
 * THE SHIPPED SET IS SESSIONS NOW. What a student is offered from the menu are
 * the very files the Save button writes -- geometry, image, notes, units and
 * the equilibrium state, in one document. Nothing is demonstrated that a
 * student could not themselves produce and hand in, which is the point of
 * choosing them that way.
 *
 * The catalogue is generated by `node tools/catalogue.js` from the files
 * themselves, so the failure to guard against is not a wrong number typed by
 * hand but a STALE one: an example added, renamed or re-saved without the
 * catalogue being rebuilt, which is a menu entry that loads nothing.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

import { deserialise, FORMAT } from '../docs/app/js/core/persist.js';
import { jointsFromBlocks } from '../docs/app/js/core/joints.js';

const DIR = new URL('../docs/app/data/examples/', import.meta.url);
const read = (f) => fs.readFileSync(new URL(f, DIR), 'utf8');
const catalogue = () => JSON.parse(read('index.json'));
const files = () => fs.readdirSync(DIR)
  .filter((f) => f.endsWith('.json') && f !== 'index.json');

test('the catalogue lists exactly what is on disk', () => {
  const listed = catalogue().examples.map((e) => e.file).sort();
  assert.deepEqual(listed, files().sort(),
    'run `node tools/catalogue.js` after adding or renaming an example');
});

test('the catalogue says what each example is for', () => {
  // A menu of eight arches with no sentence between them is a menu nobody can
  // choose from. The set exists to show the different ways of building and
  // reading an arch, so each entry has to say which.
  for (const e of catalogue().examples) {
    assert.ok(e.about && e.about.length > 20, `${e.file} has no sentence`);
    assert.ok(e.name && !e.name.endsWith('.json'), `${e.file} has no title`);
  }
});

test('the catalogue counts the blocks the files actually carry', () => {
  for (const e of catalogue().examples) {
    const raw = JSON.parse(read(e.file));
    const n = raw.format === FORMAT
      ? (raw.model?.blocks ?? []).length
      : (raw.data ?? raw).Blocks_coordinates_4_points.length;
    assert.equal(e.blocks, n, e.file);
  }
});

test('every shipped example opens, and carries its own image', () => {
  const got = files();
  assert.ok(got.length >= 5, 'the shipped set has been emptied');
  for (const f of got) {
    const raw = JSON.parse(read(f));
    assert.equal(raw.format, FORMAT, `${f} is not a session file`);
    const back = deserialise(read(f));
    assert.ok(back.model, f);
    assert.ok(back.model.blocks.length > 0, `${f} carries no blocks`);
    // SELF-CONTAINED, OR IT IS NOT AN EXAMPLE. A file that names an image it
    // does not carry opens onto a blank background and asks the student for a
    // file they do not have.
    assert.ok(back.imageData?.dataUrl?.startsWith('data:image/'),
      `${f} does not carry its background image`);
  }
});

test('every shipped example either has a joint chain or has none, consistently', () => {
  // `joints.length === blocks.length + 1` when there is a chain, and null when
  // there is not: the two are what every panel downstream indexes into, and a
  // list of the wrong length is read against the wrong joints in silence.
  let chained = 0;
  for (const f of files()) {
    const m = deserialise(read(f)).model;
    if (m.joints) {
      assert.equal(m.joints.length, m.blocks.length + 1, f);
      chained += 1;
    } else {
      // No chain is a legitimate state, and the recovery must agree that there
      // is none rather than the file simply having forgotten to store it.
      const got = jointsFromBlocks(m.blocks);
      assert.equal(got.ok, false,
        `${f} has no joints stored, but its blocks are a chain`);
      assert.ok(got.warnings[0], `${f} refuses without saying why`);
    }
  }
  assert.ok(chained >= 4,
    `only ${chained} of the shipped examples can be analysed as a chain`);
});

test('the set covers the ways an arch can be built, and both unit systems', () => {
  // The point of the set. If a future edit leaves only traced arches in metres,
  // the menu no longer shows what the application does.
  const cat = catalogue().examples;
  const methods = new Set(cat.flatMap((e) => e.groups ?? []));
  for (const want of ['three', 'draw', 'trace', 'profile']) {
    assert.ok(methods.has(want), `no example built with "${want}"`);
  }
  const units = new Set(cat.map((e) => e.units));
  assert.ok(units.size >= 2, 'every example is in the same unit system');
  assert.ok(cat.some((e) => e.loads > 0), 'no example carries an applied load');
  assert.ok(cat.some((e) => e.joints === null),
    'no example shows what the audit refuses');
});
